I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/puzzles/script.rpy", line 18, in script
    call screen puzzle_playspace(pb)
  File "renpy/common/000statements.rpy", line 609, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "renpy/common/00action_other.rpy", line 578, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/script/puzzles/room_1_puzzle_2/puzzle.rpy", line 63, in trigger_reticle
    match = sorted(match)
TypeError: '<' not supported between instances of 'Piece' and 'Piece'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/puzzles/script.rpy", line 18, in script
    call screen puzzle_playspace(pb)
  File "E:\Development\renpy-8.0.0-sdk\renpy\ast.py", line 2232, in execute
    self.call("execute")
  File "E:\Development\renpy-8.0.0-sdk\renpy\ast.py", line 2220, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "E:\Development\renpy-8.0.0-sdk\renpy\statements.py", line 281, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 609, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "E:\Development\renpy-8.0.0-sdk\renpy\exports.py", line 3181, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "E:\Development\renpy-8.0.0-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\core.py", line 4265, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\screen.py", line 743, in event
    rv = self.child.event(ev, x, y, st)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\behavior.py", line 1073, in event
    return handle_click(self.clicked)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\behavior.py", line 1008, in handle_click
    rv = run(action)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\behavior.py", line 322, in run
    new_rv = run(i, *args, **kwargs)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\behavior.py", line 329, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_other.rpy", line 578, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/script/puzzles/room_1_puzzle_2/puzzle.rpy", line 63, in trigger_reticle
    match = sorted(match)
  File "E:\Development\renpy-8.0.0-sdk\renpy\revertable.py", line 281, in revertable_sorted
    return RevertableList(sorted(*args, **kwargs))
TypeError: '<' not supported between instances of 'Piece' and 'Piece'

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
malViolence 1.0
Sat Mar 25 16:25:58 2023
