I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 192, in script
    python:
  File "renpy/common/00start.rpy", line 193, in <module>
    renpy.execute_default_statement(True)
  File "game/script/plugins/achievements.rpy", line 123, in set_default
    default achievement_dead1 = Achievement(name=achievement_name['dead1'][0], message=achievement_name['dead1'][1], image=achievement_name['dead1'][2])
Exception: store.achievement_dead1 is being given a default a second time.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 192, in script
    python:
  File "E:\Development\renpy-8.0.0-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\Development\renpy-8.0.0-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 193, in <module>
    renpy.execute_default_statement(True)
  File "E:\Development\renpy-8.0.0-sdk\renpy\exports.py", line 3782, in execute_default_statement
    i.set_default(start)
  File "game/script/plugins/achievements.rpy", line 123, in set_default
    default achievement_dead1 = Achievement(name=achievement_name['dead1'][0], message=achievement_name['dead1'][1], image=achievement_name['dead1'][2])
Exception: store.achievement_dead1 is being given a default a second time.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
malViolence 1.0
Sat Mar 25 12:12:46 2023
