I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/2 - tutorial room.rpy", line 110, in script
    if tutorial_room["vent"] == 0:
  File "game/script/2 - tutorial room.rpy", line 110, in <module>
    if tutorial_room["vent"] == 0:
NameError: name 'tutorial_room' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/2 - tutorial room.rpy", line 110, in script
    if tutorial_room["vent"] == 0:
  File "E:\Development\renpy-8.0.0-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "E:\Development\renpy-8.0.0-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "E:\Development\renpy-8.0.0-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script/2 - tutorial room.rpy", line 110, in <module>
    if tutorial_room["vent"] == 0:
NameError: name 'tutorial_room' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
malViolence 1.0
Sun Mar 19 10:36:48 2023
