I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/2 - tutorial room.rpy", line 97, in script
    "(-HURK!)" with shake
TypeError: shake() got an unexpected keyword argument 'old_widget'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/2 - tutorial room.rpy", line 97, in script
    "(-HURK!)" with shake
  File "E:\Development\renpy-8.0.0-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "E:\Development\renpy-8.0.0-sdk\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "E:\Development\renpy-8.0.0-sdk\renpy\character.py", line 1266, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "E:\Development\renpy-8.0.0-sdk\renpy\character.py", line 927, in do_display
    display_say(who,
  File "E:\Development\renpy-8.0.0-sdk\renpy\character.py", line 666, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "E:\Development\renpy-8.0.0-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\core.py", line 3752, in interact_core
    trans = self.ongoing_transition[None](
TypeError: shake() got an unexpected keyword argument 'old_widget'

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
malViolence 1.0
Mon Mar 20 12:54:18 2023
